# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each 12 hours)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: .github/github-metrics.svg
          user: mark-omarov
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Tokyo
          config_order: base.header, base.activity+community, base.repositories, achievements
          #config_display: large
          # TODO: fix achievements plugin error
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_habits: no
          # plugin_habits_days: 30
          # Disabling notable 'cause won't work with enterprise correctly
          plugin_notable: no
          plugin_notable_repositories: no
          plugin_notable_types: commit
          plugin_stars: no
          plugin_stars_limit: 4
          plugin_languages: no
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
